version: '2'
services:
  jhipstersampleapplication111-app:
    image: jhipstersampleapplication111
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jhipstersampleapplication111-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=jhipsterSampleApplication111
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  jhipstersampleapplication111-mongodb:
    extends:
      file: mongodb.yml
      service: jhipstersampleapplication111-mongodb
